apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: todoapp

spec:
      containers:
      - image: mongo
        name: mongodb
        ports:
        - name: mongodb
          containerPort: 27017
        
        volumes:
        - /data/db:/data/db
        
