version: '3'

services:
  web:
    image: web_v2:latest
    ports:
      - 8080:80
    networks:
      - my-net
    volumes:
      - /Users/junoth/Dropbox/EC601/my_flask/app:/app
  mongodb:
    image: mongo
    networks:
      - my-net
    ports:
      - 27017:27017
    volumes:
      - /data/db:/data/db
networks:
   my-net:
    driver: bridge    
