apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: todoapp

spec:
  selector:
    name: mongodb

  type: ClusterIP
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
